### ISSUE TITLE
(PR#9) 10Hz buzz on the speaker while MCPWM is idle.

### ISSUE THREAD

**Issue by dcerisano** [teckel12/arduino-toneac#11]
There is a quiet 10Hz buzz on the [ESP32](https://github.com/teckel12/arduino-toneac/pull/9) speaker while MCPWM is idle.
The issue is that the `toneAC_init()` function attaches the GPIO pins to the MCPWM, but `noToneAC()` does not detach them.

I can manually reset the pins to eliminate the buzz after calling `noToneAC()`:
```
gpio_reset_pin((gpio_num_t)MCPWM0APIN);
gpio_reset_pin((gpio_num_t)MCPWM0BPIN);
```

Then before calling `toneAC()` again, I reattach the pins to MCPWM:

```
mcpwm_gpio_init(MCPWM_UNIT_0, MCPWM0A, MCPWM0APIN);
mcpwm_gpio_init(MCPWM_UNIT_0, MCPWM0B, MCPWM0BPIN);
```

I can do a PR, but not sure if this solution is portable (works on a NODEMCU-32S)
The problem is that `toneAC_init()` is `std:call_once` so it won't re-initialize the pins automatically.

**Comment by teckel12** [comment]
@dcerisano I believe this is resolved on the v1.6.0 branch?  https://bitbucket.org/teckel12/arduino-toneac/wiki/Home
