### ISSUE TITLE
nrf52 compatibility

### ISSUE THREAD

**Issue by raffiniert** [teckel12/arduino-toneac#13]
Hey

thanks for this awesome library.
I need to use it on XIAO nrf52840 boards, but it doesn't compile, giving the following error:

`/Arduino/libraries/toneAC/src/toneAC.cpp: In function 'void toneAC(long unsigned int, uint8_t, long unsigned int, uint8_t)':
/Arduino/libraries/toneAC/src/toneAC.cpp:23:5: error: 'TIMSK1' was not declared in this scope
   23 |     TIMSK1 |= _BV(OCIE1A);            // Activate the timer interrupt.
      |     ^~~~~~
/Arduino/libraries/toneAC/src/toneAC.cpp:23:19: error: 'OCIE1A' was not declared in this scope
   23 |     TIMSK1 |= _BV(OCIE1A);            // Activate the timer interrupt.
      |                   ^~~~~~
/Arduino/libraries/toneAC/src/toneAC.cpp:23:15: error: '_BV' was not declared in this scope
   23 |     TIMSK1 |= _BV(OCIE1A);            // Activate the timer interrupt.
      |               ^~~
In file included from /Arduino/libraries/toneAC/src/toneAC.cpp:8:
/Arduino/libraries/toneAC/src/toneAC.cpp: In function 'void toneAC_playNote(long unsigned int, uint8_t)':
/Arduino/libraries/toneAC/src/toneAC.h:106:23: error: 'DDRB' was not declared in this scope
  106 |     #define PWMT1DREG DDRB
      |                       ^~~~
/Arduino/libraries/toneAC/src/toneAC.cpp:31:3: note: in expansion of macro 'PWMT1DREG'
   31 |   PWMT1DREG |= _BV(PWMT1AMASK) | _BV(PWMT1BMASK); // Set timer 1 PWM pins to OUTPUT (because analogWrite does it too).
      |   ^~~~~~~~~
/Arduino/libraries/toneAC/src/toneAC.h:104:24: error: 'DDB1' was not declared in this scope; did you mean 'B1'?
  104 |     #define PWMT1AMASK DDB1
      |                        ^~~~
/Arduino/libraries/toneAC/src/toneAC.cpp:31:20: note: in expansion of macro 'PWMT1AMASK'
   31 |   PWMT1DREG |= _BV(PWMT1AMASK) | _BV(PWMT1BMASK); // Set timer 1 PWM pins to OUTPUT (because analogWrite does it too).
      |                    ^~~~~~~~~~
/Arduino/libraries/toneAC/src/toneAC.cpp:31:16: error: '_BV' was not declared in this scope
   31 |   PWMT1DREG |= _BV(PWMT1AMASK) | _BV(PWMT1BMASK); // Set timer 1 PWM pins to OUTPUT (because analogWrite does it too).
      |                ^~~
In file included from /Arduino/libraries/toneAC/src/toneAC.cpp:8:
/Arduino/libraries/toneAC/src/toneAC.h:105:24: error: 'DDB2' was not declared in this scope; did you mean 'D2'?
  105 |     #define PWMT1BMASK DDB2`

Could you make it compatible? Also toneAC2 doesn't work either on those boards.

Thanks
Raphi

**Comment by teckel12** [comment]
As toneAC needs to use timers, it would need specific code for different types of microcontroller. So someone with the mentioned microcontroller would need to submit a pull request for support to be implemented.
