### ISSUE TITLE
Is it possible to play samples?

### ISSUE THREAD

**Issue by chonz0** [teckel12/arduino-toneac#7]
Hi there, 

(Not really an issue, but IDK where to ask this, sorry)

Would it be possible to play audio samples using this (or its big brother `toneAC2`) library?
I have some samples in the following form:
```
{127,171,185,183,176,167,158,151,142,134,130,129,130,131,127,124,123,125,125,121,115,105,97,90,80,73,69,77,}
```
which I'm currently able to play using [this functions](https://playground.arduino.cc/Code/PCMAudio/).
But I need to control the output volume, as I've done with `toneAC` in the past.

Any help would be appreciated, thanks!

PS: awesome work with this and your other libraries BTW!

**Comment by CodeSpoof** [comment]
First: toneAC2 is an inferior version. It just uses another timer, so you can play on two speakers at once.
Second: This library doesn't use PWM in the way your example does. It uses a timer and an interrupt function to play a set frequency. Playing samples is therefore not possible.

**Comment by chonz0** [comment]
Thanks! Keep up the good work 💪
