### ISSUE TITLE
A port for ESP32

### ISSUE THREAD

**Issue by jay-ramani** [teckel12/arduino-toneac#8]
Hello Tim, is there a port underway for ESP32? The existing library works flawlessly on AVRs, but would be good to see ESP32 get some of this love as well.

Thanks for your time.

Cheers.

P. S: Could you let me know how I can re-label this to enhancement or whatever suits better? I couldn't find any option to do so.

**Comment by teckel12** [comment]
@jay-ramani Please see fork 1.6.0. https://bitbucket.org/teckel12/arduino-toneac/wiki/Home
